### PR TITLE
65 fix visualizer dependencies

### LINKED ISSUE #65: Story_graph.py remove as its broken

### LINKED ISSUE #72: Story Finish Up
We need a Postman Package for the tutors to play the story without the need to send data.
At the last storypoint a telegramhijack should be performed, sending data to saved messages, and a "Game Finished by XXX" to all contributers.

### PR DESCRIPTION
**Pull request by EatingBacon**
This fixed #65 

This fixes errors with the story visualization script.
If the server is installed on something without desktop (you know, like a linux server) graphviz' view method caused an error, as it called `xdg-open [OUTPUTFILE]` to display the render result. Without a desktop environment `xdg-open` was interpreted as filename.
This error now is handled by only saving the pdf to the drive and displaying an error message that tells the user to find his outputfile there.

I also added graphviz install to `manage.sh install`, so it will be added to the path during install (this is a known issue with the python graphviz lib). Therefore superuser now is needed to call `manage.sh install`

### CODE REVIEW

File: manage.sh [hunk 1]
```diff
@@ -17,6 +17,7 @@ if [ "$command" == "install" ]; then
     source .venv/bin/activate
     pip install --upgrade pip
     pip install -r requirements.txt
+    sudo apt install graphviz
```
Comment (robinwersich) [inline manage.sh]: this will throw an error on dists with pacman...
but I think something like `sudo apt install graphviz || pacman -S graphviz` could work
I'll test this
